---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app
  namespace: dev
  labels:
    app:  app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app:  app
    spec:
      containers:
      - name:  mahmoudk1000/app
        image:  mahmoudk1000/app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
  - name: app
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring_app
  labels:
    app: app
    release: monitoring
spec:
  endpoints:
  - path: /metrics
    port: service
    targetPort: 5000
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: app
