---
- name: Wait for ssh connection
  hosts: _Name_dev_server
  gather_facts: False
  tasks:
    - name: Ensure port 22
      vars:
        ansible_python_interpreter: /usr/bin/python
        ansible_connection: local
      wait_for:
        port: 22
        delay: 10
        timout: 30
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'


- name: Install python3, docker and docker-compose with python modules
  hosts: _Name_dev_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present

    - name: Fetch docker-compose bin
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-armv6
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Install python modules
      pip:
        name:
          - docker
          - docker-compose


- name: Docker service up
  hosts: _Name_dev_server
  become: yes
  tasks:
    - name: Enable docker daemon
      systemd:
        name: docker
        state: started


- name: Activelly append ec2-user to docker group
  hosts: _Name_dev_server
  become: yes
  tasks:
    - name: Add user ec2-user to dokcer
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Exec bash
      meta: reset_connection


- name: Pull and start app docker container
  hosts: _Name_dev_server
  tasks:
    - name: Pull Docker image
      docker_image:
        name: app:latest
        source: pull
      register: pulled_image

    - name: Start Docker container
      docker_container:
        name: app
        image: "{{ pulled_image.name }}"
        state: started
        ports:
          - "5000:5000"
